#!/usr/bin/env bash
set -e

#export APPLIANCE=deiis
make_docker=false
if [ "$1" = "-b" ] ; then
	make_docker=true
	shift
fi

export APPLIANCE=$1
shift

if [ -d build ] ; then
	echo "Cleaning up from a previous build."
	rm -rf build
fi
cp -R galaxy build

groovy YamlBuilder.groovy $APPLIANCE $@ > docker-compose.yml

while [ -n "$1" ] ; do
	echo "Building $1"
	cp -R $1/tools build
	if [ -z "$2" ] ; then
		# Minimize (remove empty sections) when building the final tool_conf.xml
		OPTS="-m"
	fi
	tce $OPTS -c build/tool_conf.xml -o build/tool_conf.xml $1/tool_conf.groovy
	if [ "$make_docker" = "true" ] ; then
		cd $1 
		make
		cd -
	fi
	shift
done

cd build
make

